version: '3.8'

services:
  # A2A Agent Registry Backend
  registry:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/a2a_registry
      - REDIS_URL=redis://redis:6379/0
      - OPENSEARCH_URL=http://opensearch:9200
      - SECRET_KEY=dev-secret-key
      # Bootstrap API key auth for demo (Bearer). Use only in dev.
      - API_KEYS=["dev-admin-api-key"]
      - API_KEY_DEFAULT_ROLES=["Administrator","User"]
    depends_on:
      - db
      - redis
      - opensearch
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend removed in core-only build

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=a2a_registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # OpenSearch
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/opensearch/data

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
