# Simple Chatbot Agent Configuration
# This is a basic example of an A2A agent configuration file

name: "simple-chatbot"
description: "A simple AI chatbot that can answer questions and have conversations"
version: "1.0.0"
provider: "chatbot-inc"
tags:
  - "ai"
  - "chatbot" 
  - "conversation"
  - "nlp"

is_public: true
is_active: true

location_url: "https://api.chatbot-inc.com/v1/agent"
location_type: "api_endpoint"

# Agent capabilities
capabilities:
  protocols:
    - "http"
    - "websocket"
  supported_formats:
    - "json"
  max_request_size: 1048576  # 1MB
  max_concurrent_requests: 10
  a2a_version: "1.0"

# Authentication schemes
auth_schemes:
  - type: "api_key"
    description: "API key authentication"
    required: true
    header_name: "X-API-Key"

# Agent card with detailed metadata
agent_card:
  name: "simple-chatbot"
  description: "A simple AI chatbot that can answer questions and have conversations"
  version: "1.0.0"
  author: "Chatbot Inc"
  api_base_url: "https://api.chatbot-inc.com/v1"
  
  capabilities:
    protocols:
      - "http"
      - "websocket"
    supported_formats:
      - "json"
    max_request_size: 1048576
    max_concurrent_requests: 10
    a2a_version: "1.0"
  
  auth_schemes:
    - type: "api_key"
      description: "API key authentication"
      required: true
      header_name: "X-API-Key"
  
  endpoints:
    chat: "/chat"
    status: "/status"
    capabilities: "/capabilities"
  
  skills:
    input_schema:
      type: "object"
      properties:
        message:
          type: "string"
          description: "User message or question"
        context:
          type: "object"
          description: "Optional conversation context"
      required:
        - "message"
    
    output_schema:
      type: "object"
      properties:
        response:
          type: "string"
          description: "Chatbot response"
        confidence:
          type: "number"
          minimum: 0.0
          maximum: 1.0
          description: "Response confidence score"
      required:
        - "response"
        - "confidence"
    
    examples:
      - "Input: {'message': 'Hello'} -> Output: {'response': 'Hi there! How can I help you?', 'confidence': 0.95}"
      - "Input: {'message': 'What is AI?'} -> Output: {'response': 'AI is artificial intelligence...', 'confidence': 0.88}"
