# Simple Chatbot Agent Configuration
# This is a basic example of an A2A agent configuration file following the official specification

name: "Simple Chatbot"
description: "A simple AI chatbot that can answer questions and have conversations"
url: "https://api.chatbot-inc.com/v1/agent"
provider:
  organization: "Chatbot Inc"
  url: "https://chatbot-inc.com"
version: "1.0.0"
documentationUrl: "https://api.chatbot-inc.com/v1/docs"

# Agent capabilities following A2A specification
capabilities:
  streaming: true
  pushNotifications: false
  stateTransitionHistory: true

# Authentication requirements
authentication:
  schemes: ["Bearer", "API-Key"]
  credentials: "api_key_for_chatbot_access"

# Default interaction modes
defaultInputModes: ["text/plain", "application/json"]
defaultOutputModes: ["text/plain", "application/json"]

# Skills array following A2A specification
skills:
  - id: "general_chat"
    name: "General Chat"
    description: "Handle general conversations and answer questions"
    tags: ["chat", "conversation", "general", "nlp"]
    examples:
      - "Hello, how are you?"
      - "What is artificial intelligence?"
      - "Tell me a joke"
    inputModes: ["text/plain"]
    outputModes: ["text/plain"]

  - id: "question_answering"
    name: "Question Answering"
    description: "Answer specific questions with detailed responses"
    tags: ["qa", "questions", "answers", "knowledge"]
    examples:
      - "What is the capital of France?"
      - "How does photosynthesis work?"
      - "Explain quantum computing"
    inputModes: ["text/plain", "application/json"]
    outputModes: ["text/plain", "application/json"]

  - id: "conversation_context"
    name: "Contextual Conversation"
    description: "Maintain conversation context and provide follow-up responses"
    tags: ["context", "conversation", "follow-up", "memory"]
    examples:
      - "Continue our previous discussion about AI"
      - "Based on what I told you earlier..."
      - "Remember when we talked about..."
    inputModes: ["application/json"]
    outputModes: ["application/json"]

  - id: "sentiment_analysis"
    name: "Sentiment Analysis"
    description: "Analyze the emotional tone and sentiment of user messages"
    tags: ["sentiment", "emotion", "analysis", "nlp"]
    examples:
      - "How does this message sound?"
      - "Is the user happy or sad?"
      - "Analyze the emotional tone"
    inputModes: ["text/plain"]
    outputModes: ["application/json"]
